name: build

on:
    push:
        branches: [ main ]

jobs:
    build:
        name: build

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Build and publish
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: tonybogdanov/zip
                  username: Christ05
                  password: ${{ secrets.DOCKERPASSWORD }}
