name: first github action

on:
    push:
        branches: [ main ]

jobs:
    build:
        name: build

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Build and publish
              uses: elgohr/Publish-Docker-Github-Action@master
            - name: test
              run: npm test
