name: integration continue

on:
    push:
        branches: [ main ]

jobs:
        app-test:
      

        runs-on: ubuntu-latest
        default:
         run:
          working-directory: front-end
        steps:
          
              uses: actions/checkout@v1
            - name: test
              run: npm test
    integration-test:
         runs-on: ubuntu-latest

    build-image:
        runs-on: ubuntu-latest

            
    steps:
    - uses: actions/checkout@v3

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with: 
        context: ${{ matrix.component }}
        file: ${{ matrix.component }}/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/spm-${{ matrix.component }}:${{ github.ref_name }}   